### PR TITLE
introduce invalidate vcl

### PR DESCRIPTION
**Pull request by gquintard**

### CODE REVIEW

**Comment by aondio** [comment]
Very nice.
Some feedback for the naming:
* ZERO and RMTAG are not intuitive to me. I had to read the VCL to understand what was doing what. 
Maybe use PURGEALL and PURGETAG?


I'm also thinking if the access control logic should belong to the invalidate.vcl or not.
We could also have a access_control.vcl and an invalidate.vcl

So you would have main.vcl which calls first the access_control.vcl and afterwards the invalidate.vcl
This will make life easier to our customers.

**Comment by gquintard** [comment]
would:
- `PURGE` -> `PURGEONE`
- `BAN` -> `PURGEDIR`
- `ZERO` -> `PURGEALL`
- `RMTAG` -> `PURGETAG`
work?

I'm not sure how to go about the access control without going crazy with all the possibilities. But maybe just focusing on `cookie`, `authorization`, and ACL (in Enterprise using `aclplus`), while still letting the VCL writer override the authorization?

**Comment by rezan** [comment]
I think `PURGE` and `BAN` should remain as is. They have established meanings in this context. +1 on `PURGEALL` and `PURGETAG`.

**Comment by gquintard** [comment]
my main issue is that we conflate the action with the implementation (`PURGEALL` isn't using `purge`, and `BAN` is technically using a `ban` but severly focusing its action), which can make explaining to newcomers confusing, but if I'm the only one bothered by it, let's go with `PURGEALL`, `PURGETAG` and some semantics explanation

**Comment by rezan** [comment]
I see what your saying about `BAN`. Might be worth investigating how to incorporate a more flexible and free form expression...

**Comment by gquintard** [comment]
How about `BANDIR` and `BANALL` for the current ones, and we reserves `BAN` for a future, more liberal method (which could be off by default)?

I didn't plan on a comprehensive implementation but to have something that would both be an off-the-shelf and sufficient implementation for most use-cases and and example for VCL writers. I think the current state fulfill both requirements, so I'm in no rush to implement a generic `BAN` method, but we shouldn't paint ourselves in a corner

**Comment by gquintard** [comment]
merged with 2b470e7

**Pull request closed without merging**
